### ISSUE TITLE
Libevdev.next_event isn't thread-friendly

### ISSUE THREAD

**Issue by xetum** [christopheraue/ruby-libevdev#1]
Should be marked as blocking in `lib/libevdev/generated/libevdev.rb`:

    attach_function :libevdev_next_event, [ :pointer, :uint, :pointer ], :int, :blockig => true

otherwise, when used in a thread, blocks app because gvl (ruby global VM lock) isn't released.

Regards, Francesc

**Comment by christopheraue** [comment]
Thanks for the hint. Do you mind creating a pull request? The interface file is generated with `rake generate` which uses SWIG (see https://github.com/christopheraue/ruby-libevdev/blob/master/tasks/ffi.rake). SWIG probably doesn't know anything about blocking functions. So, probably just change that line manually after generation (like I already did for other cases).

**Comment by christopheraue** [comment]
Fixed by #2

**Comment by alxx** [comment]
Is this really fixed though? I've tested it and, when used in a thread, it still blocks the app.
